// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package repository

import (
	"database/sql"
)

type AccountDetail struct {
	ID          string
	Name        sql.NullString
	CompanyName sql.NullString
	Email       string
	Mobile      sql.NullString
	Roles       sql.NullString
	City        sql.NullString
	Password    string
}

type Booking struct {
	ID               string
	BookingRequestID string
	BookingStatus    sql.NullString
	CustomerID       sql.NullString
	Source           sql.NullString
	Destination      sql.NullString
}

type BookingMilestone struct {
	ID              string
	BookingID       sql.NullString
	MilestoneID     sql.NullString
	MilestoneStatus sql.NullString
	CreatedAt       sql.NullString
	CompletedAt     sql.NullString
}

type BookingTask struct {
	ID          string
	BookingID   sql.NullString
	TaskID      sql.NullString
	TaskStatus  sql.NullString
	CreatedAt   sql.NullString
	CompletedAt sql.NullString
}
type Liner struct {
	ID   string
	Name sql.NullString
}

type Milestone struct {
	ID   string
	Name sql.NullString
}

type Partner struct {
	ID   string
	Name sql.NullString
}

type Quote struct {
	ID              string
	QuoteType       string
	CustomerID      string
	Source          string
	Destination     string
	DoorPickup      sql.NullString
	DoorAddress     sql.NullString
	DoorDelivery    sql.NullString
	DeliveryAddress sql.NullString
	LinerID         sql.NullString
	PartnerID       sql.NullString
	Validity        sql.NullString
	TransmitDays    sql.NullString
	FreeDays        sql.NullString
	Currency        sql.NullString
	Buy             sql.NullString
	Sell            sql.NullString
	PartnerTax      sql.NullString
	QuoteStatus     sql.NullString
}

type Task struct {
	ID   string
	Name sql.NullString
}
